version: "3.9"

services:
  client:
    build:
      context: ./email-service-client
    ports:
      - 8081:8081
    volumes:
      - ./email-service-client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./email_server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./email_server:/usr/src/app
      - ./storage:/usr/src/app/storage
    command: ["cargo", "run"]
